apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-config
  namespace: kube-system
data:
  values.yaml: |
    domainFilters:
      - luke.infra-coders.com
    txtOwnerId: Z02251092DC8UV3YZXE7B
