---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: ExternalArtifact
    name: apps
  path: "./base/capacitor"
  prune: true
